name: CICD

on: [push]
#  push:
#    branches:
#      - master

jobs:
  check_build_web:
    name: Check build web
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build web app
        run: |
          cd NsauT.Web
          dotnet build --configuration Release

  deploy:
    needs: [check_build_web]
    name: Deploy to VPS
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Push to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/projects/nsau_timetable/
            #git checkout master
            git checkout fix_scriptInGithubActions
            git pull
            if [ -f deploy.sh ]
            then bash deploy.sh ${{ secrets.DB_CONNECTION_STRING}}
            else echo "deploy script not found"
            fi
